version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: application-back/Dockerfile
    container_name: application-back
    environment:
      DATABASE_URL: "mysql://user:password@db:3306/database"
    ports:
      - "8000:8000"
    depends_on:
      - db


  frontend:
    build:
      context: .
      dockerfile: application-front/Dockerfile
    co,tainer_name: application-front
    ports:
      - "3000:80"
    depends_on:
      - api
    environment:
      - REACT_APP_API_URL=http://application-back:8000

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"  
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: