lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600  # 1 heure (3600 secondes)
    token_extractors:
        authorization_header: # Par défaut, active le header `Authorization`
            enabled: true
            prefix:  Bearer
        query_parameter: # Active l'extraction des tokens dans l'URL
            enabled: true
            name:    token # Nom du paramètre utilisé pour passer le token dans l'URL

  
