nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:3000']  # Autoriser votre application React
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Content-Disposition', 'Content-Type']
        allow_methods: ['POST', 'GET', 'OPTIONS','DELETE', 'PUT']
        max_age: 3600

    paths:
        '^/drive_API/':  # Ajustez le chemin selon votre API
            allow_origin: ['http://localhost:3000']  # Autoriser votre application React
            allow_headers: ['Content-Type', 'Authorization']
            expose_headers: ['Content-Disposition', 'Content-Type']
            allow_methods: ['POST', 'GET', 'OPTIONS','DELETE','PUT']
            max_age: 3600